-- require("items.widgets.control_center")
-- require("items.widgets.keyboard_layout")
require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu")
